

// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by T4 Template.
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Resources;

namespace Kool.VsDiff
{
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings.
    /// </summary>
    static class VSPackage
    {
        static readonly ResourceManager Resx = new ResourceManager("Kool.VsDiff.VSPackage", typeof(VSPackage).Assembly);

        public static string _110 { get; } = Resx.GetString("110");
        public static string _112 { get; } = Resx.GetString("112");
        public static string ErrorMessageTitle { get; } = Resx.GetString("ErrorMessageTitle");
        public static string OptionsPage_Arguments { get; } = Resx.GetString("OptionsPage_Arguments");
        public static string OptionsPage_DiffToolPath { get; } = Resx.GetString("OptionsPage_DiffToolPath");
        public static string OptionsPage_EnableDiagnosticsMode { get; } = Resx.GetString("OptionsPage_EnableDiagnosticsMode");
        public static string OptionsPage_EnableDiffClipboardWithCode { get; } = Resx.GetString("OptionsPage_EnableDiffClipboardWithCode");
        public static string OptionsPage_EnableDiffClipboardWithDocument { get; } = Resx.GetString("OptionsPage_EnableDiffClipboardWithDocument");
        public static string OptionsPage_EnableDiffClipboardWithFile { get; } = Resx.GetString("OptionsPage_EnableDiffClipboardWithFile");
        public static string OptionsPage_TestButtonContent { get; } = Resx.GetString("OptionsPage_TestButtonContent");
        public static string OptionsPage_UseCustomDiffTool { get; } = Resx.GetString("OptionsPage_UseCustomDiffTool");
    }
}