// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by T4 Template.
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Resources;

namespace Kool.VsDiff
{
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings.
    /// </summary>
    static class I18n
    {
        static readonly ResourceManager Resx = new ResourceManager("VSPackage", typeof(I18n).Assembly);

        public static string ErrorMessageTitle { get; } = Resx.GetString("ErrorMessageTitle");
        public static string OptionsPage_Arguments { get; } = Resx.GetString("OptionsPage_Arguments");
        public static string OptionsPage_DiffToolPath { get; } = Resx.GetString("OptionsPage_DiffToolPath");
        public static string OptionsPage_EnableDiffClipboardWithCode { get; } = Resx.GetString("OptionsPage_EnableDiffClipboardWithCode");
        public static string OptionsPage_EnableDiffClipboardWithDocument { get; } = Resx.GetString("OptionsPage_EnableDiffClipboardWithDocument");
        public static string OptionsPage_EnableDiffClipboardWithFile { get; } = Resx.GetString("OptionsPage_EnableDiffClipboardWithFile");
        public static string OptionsPage_EnableDiffSelectedFiles { get; } = Resx.GetString("OptionsPage_EnableDiffSelectedFiles");
        public static string OptionsPage_PreferToUsePreviewWindow { get; } = Resx.GetString("OptionsPage_PreferToUsePreviewWindow");
        public static string OptionsPage_TestButtonContent { get; } = Resx.GetString("OptionsPage_TestButtonContent");
        public static string OptionsPage_UseCustomDiffTool { get; } = Resx.GetString("OptionsPage_UseCustomDiffTool");
    }
}