// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "VSTHRD010:Accessing \"Document\" should only be done on the main thread. Call Microsoft.VisualStudio.Shell.ThreadHelper.ThrowIfNotOnUIThread() first.", Justification = "<Pending>", Scope = "member", Target = "~M:Kool.VsDiff.Commands.DiffClipboardWithCodeCommand.OnExecute")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "VSTHRD010:Accessing \"TextSelection\" should only be done on the main thread. Call Microsoft.VisualStudio.Shell.ThreadHelper.ThrowIfNotOnUIThread() first.", Justification = "<Pending>", Scope = "member", Target = "~M:Kool.VsDiff.Commands.DiffClipboardWithCodeCommand.TryGetSelectionText~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "VSTHRD010:Accessing \"Document\" should only be done on the main thread. Call Microsoft.VisualStudio.Shell.ThreadHelper.ThrowIfNotOnUIThread() first.", Justification = "<Pending>", Scope = "member", Target = "~M:Kool.VsDiff.Commands.DiffClipboardWithDocumentCommand.TryGetDocumentActiveDocumentFile(System.String@)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "VSTHRD010:Accessing \"IVsOutputWindowPane\" should only be done on the main thread. Call Microsoft.VisualStudio.Shell.ThreadHelper.ThrowIfNotOnUIThread() first.", Justification = "<Pending>", Scope = "member", Target = "~M:Kool.VsDiff.Models.VS.OutputWindow.Initialize")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "VSTHRD010:Accessing \"IVsOutputWindowPane\" should only be done on the main thread. Call Microsoft.VisualStudio.Shell.ThreadHelper.ThrowIfNotOnUIThread() first.", Justification = "<Pending>", Scope = "member", Target = "~M:Kool.VsDiff.Models.VS.OutputWindow.WriteLine(System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "VSTHRD010:Accessing \"SelectedItems\" should only be done on the main thread. Call Microsoft.VisualStudio.Shell.ThreadHelper.ThrowIfNotOnUIThread() first.", Justification = "<Pending>", Scope = "member", Target = "~M:Kool.VsDiff.Models.VS.SolutionExplorer.GetFiles(EnvDTE.SelectedItems)~System.Collections.Generic.List{System.String}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "VSTHRD010:Accessing \"SelectedItems\" should only be done on the main thread. Call Microsoft.VisualStudio.Shell.ThreadHelper.ThrowIfNotOnUIThread() first.", Justification = "<Pending>", Scope = "member", Target = "~M:Kool.VsDiff.Models.VS.SolutionExplorer.TryGetSelectedFiles(System.String@,System.String@)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "VSTHRD010:Accessing \"SelectedItems\" should only be done on the main thread. Call Microsoft.VisualStudio.Shell.ThreadHelper.ThrowIfNotOnUIThread() first.", Justification = "<Pending>", Scope = "member", Target = "~M:Kool.VsDiff.Models.VS.SolutionExplorer.TryGetSingleSelectedFile(System.String@)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "VSTHRD010:Accessing \"IVsDifferenceService\" should only be done on the main thread. Call Microsoft.VisualStudio.Shell.ThreadHelper.ThrowIfNotOnUIThread() first.", Justification = "<Pending>", Scope = "member", Target = "~M:Kool.VsDiff.Models.VsDiffTool.#ctor(Kool.VsDiff.VsDiffPackage)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "VSTHRD010:Accessing \"IVsDifferenceService\" should only be done on the main thread. Call Microsoft.VisualStudio.Shell.ThreadHelper.ThrowIfNotOnUIThread() first.", Justification = "<Pending>", Scope = "member", Target = "~M:Kool.VsDiff.Models.VsDiffTool.Diff(System.String,System.String,System.Action{System.String,System.String})")]